### ISSUE TITLE
Azure AKS inaccurate cost report

### ISSUE THREAD

**Issue by andre-adam-randoli** [opencost/opencost#2090]
**Describe the bug**
The daily cost report for an AKS cluster is off, based on Azures Cost Analysis the cost for a day is around 19 CAD but OpenCost reports around 10.50 USD. I have followed the configuration steps on https://www.opencost.io/docs/configuration/azure-prices, we don't have any customer-specific pricing, just a normal Azure plan on-demand subscription.

Are there any other configurations I can do?

Also, is there a way to confirm the Azure service key configuration worked as expected? I don't see any errors or warnings regarding it but also could not find any successful logs about it.

**To Reproduce**
1. Go to OpenCost UI, select Yesterday as the Date range, get the total for the cluster
2. Go to Azure Cost Analysis service, select yesterday's date, and check total
3. Compare values

**Expected behavior**
I expected the total cost to be closer to the one reported by Azure

**Which version of OpenCost are you using?**
1.105.1, installed with Helm chart, used the tag in the values.yaml

**Additional context**
Running on Azure AKS, AKS managed node groups, Kubernetes version is v1.25.6

Any help is appreciated.

**Comment by mattray** [comment]
Just a quick clarifying question, are both UI's using the same timezone?

**Comment by mattray** [comment]
Did you delete a node? There's an issue with 1.105.0 and 1.105.1 that may be responsible for this issue.

**Comment by andre-adam-randoli** [comment]
[opencost-01.log](https://github.com/opencost/opencost/files/12419914/opencost-01.log)
Had to look up to confirm but yes Azure Cost Analysis only displays UTC and the query I made was also using UTC.

I didn't delete any nodes, actually, one node was added in this cluster since the OpenCost installation but the price is still off. I tried both versions to check, still same prices.

I think there is an issue querying for the node prices, logs say that the nodes are found in Prometheus but not in k8s API, I'll attach it.
Also, I have added azureBillingRegion=CA, azureOfferDurableID=MS-AZR-0017g, and currencyCode=CAD to a pricing-configs ConfigMap, but the UI still displayed the same prices as before, even after a couple of days.
Instesting enough, the price returned by the metrics endpoint is actually very close to the one in Azure, I checked the "node_total_hourly_cost" for each node and calculated the total for a day and it was only a few cents off.

**Comment by mattray** [comment]
That sounds exactly like the issue resolved by 1.105.2. Nodes are no longer in K8s but they weren't marked as removed in Prometheus, so they continue to accrue charges (in Prometheus, not your actual bill). I'm going to close this, but please upgrade to 1.105.2 and see if it resolves your issue. Once there's a cleanup for Prometheus data available I'll update the release notes for [1.105.2](https://github.com/opencost/opencost/releases/tag/v1.105.2). 

If this is incorrect, please reopen the issue with updates accordingly. Thanks!

**Comment by andre-adam-randoli** [comment]
Hey @mattray,

I'm back on this issue, I updated to the latest version but still having the same issue, I still see the log "Node `aks-default-<id>-<name>` in prometheus but not k8s api" and "No pricing data found for node `<IP>` , using custom pricing".
The metric "node_total_hourly_cost" in Prometheus is reporting a more accurate price but the OpenCost backend returns a different daily price.

Anything else I'm able to do?
If you need more details please let me know.
