### ISSUE TITLE
Can't get GCP billing data from EU region

### ISSUE THREAD

**Issue by SorsOps** [opencost/opencost#2755]
**Describe the bug**
Can't get GCP billing data for big query if not in location US

**To Reproduce**
1. Create a GCP account and export the billing info from the EU region
2. Attempt to read it 

**Expected behavior**
That it either should read the data or give me the ability to configure the region

**Screenshots**

```
64266Z INF CloudCost[<REDACTED>/<REDACTED>.<REDACTED>]: ingestor: building window [2024-05-01T00:00:00+0000, 2024-05-08T00:00:00+0000)
2024-05-19T19:05:58.753164267Z ERR CloudCost[<REDACTED>/<REDACTED>.<REDACTED>]: ingestor: build failed for window [2024-05-12T00:00:00+0000, 2024-05-19T00:00:00+0000): error retrieving CUD rates: GetFlexibleCUDRates: queryCUDAmountPayed: query error BigQueryQuerier: Query: error reading query results: googleapi: Error 404: Not found: Dataset<REDACTED>:d<REDACTED> was not found in location US, notFound
```

**Which version of OpenCost are you using?**

- ghcr.io/opencost/opencost-ui:1.110.0

**Comment by mattray** [comment]
That looks like what I fixed in https://github.com/opencost/opencost/pull/2239

**Comment by mattray** [comment]
This should be fixed in the next release

**Comment by GaMartinelli** [comment]
Still seeing this issue on v1.111

Cluster is running in europe-west3 region. Not sure if something related to the region should be set during during the installation, just followed the steps in docs/configuration/gcp

`2024-09-20T02:31:35.326841108Z INF Starting cost-model version 1.111 (1dd2e52)
[...]
2024-09-20T02:31:47.013855318Z INF CloudCost[REDACTED/detailedbilling.gcp_billing_export_resource_v1_0121AC_C6F51B_690771]: ingestor: build[SLpFR]:  [2024-09-13T00:00:00+0000, 2024-09-20T00:00:00+0000) in 1.014658535s
2024-09-20T02:31:47.013881401Z INF CloudCost[REDACTED/detailedbilling.gcp_billing_export_resource_v1_0121AC_C6F51B_690771]: ingestor: building window [2024-09-06T00:00:00+0000, 2024-09-13T00:00:00+0000)
2024-09-20T02:31:47.040326469Z ERR CloudCost[REDACTED/detailedbilling.gcp_billing_export_resource_v1_0121AC_C6F51B_690771]: ingestor: build failed for window [2024-09-01T00:00:00+0000, 2024-09-08T00:00:00+0000): error retrieving CUD rates: GetFlexibleCUDRates: queryCUDAmountPayed: query error BigQueryQuerier: Query: error reading query results: googleapi: Error 404: Not found: Dataset REDACTED:detailedbilling was not found in location US, notFound
`

**Comment by ioboi** [comment]
Hello 👋 

I encountered the same issue in our environment:

```
ERR CloudCost[xxx]: ingestor: build failed for window [2026-05-01T00:00:00+0000, 202 │
│ 6-05-08T00:00:00+0000): error retrieving CUD rates: GetFlexibleCUDRates: queryCUDAmountPayed: query error BigQueryQuerier: Query: error reading query results: googleapi: Error 404: Not found: Dataset xxx was not found in location US, notFound
```

We are located in the EU.
